### ISSUE TITLE
Remove White Background From Slide Img

### ISSUE THREAD

**Issue by dezmoni** [vinayakjadhav/jRCarousel#1]
How might one alter this code to remove the white background from the images and also not show the target images behind the current image slide?

I've managed to make the background transparent however it is not clear how to not show images behind the current slide.

**Comment by vinayakjadhav** [comment]
I kept the background white so that effect would be more visible. If the background is made transparent then while transitioning the current image is also shown which makes the effect less "visible". As per your second comment if not image then what should be in the background?

**Comment by dezmoni** [comment]
I just wanted to see if it were possible to get rid of the white background while also, hiding the images that show behind the current slide with this code.

**Comment by vinayakjadhav** [comment]
yes, white background can be removed, but then the image would be shown, if you dont want the image also then what do you expect to be seen, let me know, I'll check it out.

**Comment by dezmoni** [comment]
I want nothing to be shown but the current image with a transparent background. As of now, If you change the background to transparent the front image is shown but you can also see the rest of the other images layered behind the current side. The layered images that are visible behind the current slide with a transparent background are what I want to hide. What i expect to see is nothing behind the current slide, just the current slide with its transparent background.

**Comment by vinayakjadhav** [comment]
In that case I would suggest simply set the background color of carousel same as the background color of page. That way background images wont be visible & it would do the trick.

**Comment by dezmoni** [comment]
Except the background is not a solid color, its an image and it is imperative that the background be transparent.

the carousel is inside a div that is on the page:

`<div id="slideshow-container">
      <div class="jRCarouselGallery"></div>
    </div>`

where  **slideshow-container** has a background image to it that stretches 100% width of the page.

**Comment by dezmoni** [comment]
Thanks for you help btw.

**Comment by vinayakjadhav** [comment]
Thanks Harris.
